
version: '3'
services:
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        restart: always
        volumes:
            - /mnt:/mnt
        ports:
            - 80:80
    flask:
        build:
            context: flask
            dockerfile: Dockerfile
        restart: always
        command: python app.py
        environment:
            - DATADIR=/mnt/hd2/data/Totalsegmentator_dataset
        volumes:
            - /mnt:/mnt
            - ${PWD}/flask:/opt
        expose:
            - 5000
