
version: '3'
services:
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
    flask:
        build:
            context: flask
            dockerfile: Dockerfile
        restart: always
        command: python app.py
        env_file:
            - .env
        expose:
            - 5000
