
version: '3'
services:
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        restart: always
        volumes:
            - /mnt:/mnt
        ports:
            - 80:80
    flask:
        build:
            context: flask
            dockerfile: Dockerfile
        restart: always
        command: python app.py
        environment:
            - DATADIR_TOTALSEG=/mnt/hd2/data/Totalsegmentator_dataset
            - DATADIR_PEDCTSEG=/mnt/hd2/data/ped-ct-seg-nifti
            - DATADIR_AMOS22=/mnt/hd2/data/amos22
        volumes:
            - /mnt:/mnt
            - ${PWD}/flask:/opt
        expose:
            - 5000
